import _API_INSTANCE from "@/utils/axios";

export const _BADGES = {
  learningProgress: [
    {
      id: "firstStep",
      name: "First Step",
      description:
        "Created the first note, first flashcards set, and first quiz.",
    },
    {
      id: "quickLearner",
      name: "Quick Learner",
      description: "Achieved at least 80% score on 5 different quizzes.",
    },
    {
      id: "noteTaker",
      name: "Note Taker",
      description: "Created 10 personal notes or summaries.",
    },
    {
      id: "flashcardMaster",
      name: "Flashcard Master",
      description: "Created 10 flashcard sets.",
    },
    {
      id: "masterReviewer",
      name: "Master Reviewer",
      description: "Answered and reviewed the same quiz at least 5 times.",
    },
  ],
  collaborationCommunity: [
    {
      id: "firstPost",
      name: "First Post",
      description:
        "Shared a post with your first attachment (summary notes, flashcard set, or quiz set) to the forum.",
    },
    {
      id: "helpfulCommenter",
      name: "Helpful Commenter",
      description: "Received 10 upvotes across your comments",
    },
    {
      id: "communityFavorite",
      name: "Community Favorite",
      description:
        "One of your posts with any attached shared materials received 25 upvotes from different users.",
    },
  ],
  milestonesAchievements: [
    {
      id: "perfectionist",
      name: "Perfectionist",
      description: "Achieved 100% score on a quiz.",
    },
    {
      id: "achiever",
      name: "Achiever",
      description: "Achieved 100% score on 10 different quizzes.",
    },
    {
      id: "forumVeteran",
      name: "Forum Veteran",
      description:
        "Participated in 100+ forum activities (votes, comments, shares)",
    },
  ],
};

/**
 * A map of badge IDs to their corresponding badge objects.
 *
 * This constant is generated by flattening all badge arrays from `_BADGES`,
 * then reducing them into an object where each key is a badge's `id` and the value
 * is the badge object itself.
 *
 * @remarks
 * The resulting map allows for efficient lookup of badge details by their ID.
 *
 * @example
 * ```typescript
 * const badge = _BADGE_MAP['badge123'];
 * console.log(badge.name); // Outputs the name of the badge with ID 'badge123'
 * ```
 */
export const _BADGE_MAP = Object.values(_BADGES)
  .flat()
  .reduce(
    (acc, badge) => {
      acc[badge.id] = badge;
      return acc;
    },
    {} as Record<string, { id: string; name: string; description: string }>
  );

/**
 * USED FOR COMPONENTS NGA NAAY BADGES, para dali ra mag import sa useAssets
 * A mapping of badge identifiers to their corresponding image assets.
 * Each key represents a badge name, and the value is the required image asset for that badge.
 *
 * Badge keys include:
 * - `firstStep`
 * - `quickLearner`
 * - `noteTaker`
 * - `flashcardMaster`
 * - `masterReviewer`
 * - `firstPost`
 * - `helpfulCommenter`
 * - `communityFavorite`
 * - `perfectionist`
 * - `achiever`
 *
 * Used to display badge images in the application.
 */
export const _BADGE_ASSET_MAP: Record<string, any> = {
  firstStep: require("../../assets/images/badges/first-step-gradient.png"),
  quickLearner: require("../../assets/images/badges/quick-learner-gradient.png"),
  noteTaker: require("../../assets/images/badges/note-taker-gradient.png"),
  flashcardMaster: require("../../assets/images/badges/flashcard-master-gradient.png"),
  masterReviewer: require("../../assets/images/badges/master-reviewer-gradient.png"),
  firstPost: require("../../assets/images/badges/first-post-gradient.png"),
  helpfulCommenter: require("../../assets/images/badges/helpful-commenter-gradient.png"),
  communityFavorite: require("../../assets/images/badges/community-favorite-gradient.png"),
  perfectionist: require("../../assets/images/badges/perfectionist-gradient.png"),
  achiever: require("../../assets/images/badges/achiever-gradient.png"),
};

/**
 * Checks the user's badges by making an API request to the "badges/check" endpoint.
 * If successful, retrieves the awarded badges from the response data.
 * Logs an error message to the console if the request fails.
 *
 * @returns {Promise<void>} A promise that resolves when the badge check is complete.
 */
export async function checkBadges() {
  try {
    const { data } = await _API_INSTANCE.get("badges/check");
  } catch (err) {
    console.error("Badge check failed", err);
  }
}
