
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.13.0
 * Query Engine version: 361e86d0ea4987e9f53a565309b3eed797a6bcbd
 */
Prisma.prismaVersion = {
  client: "6.13.0",
  engine: "361e86d0ea4987e9f53a565309b3eed797a6bcbd"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  password: 'password',
  first_name: 'first_name',
  last_name: 'last_name',
  email: 'email',
  gender: 'gender',
  phone_number: 'phone_number',
  badges: 'badges',
  is_public: 'is_public',
  created_at: 'created_at',
  updated_at: 'updated_at',
  is_admin: 'is_admin'
};

exports.Prisma.FlashcardScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  description: 'description',
  flashcards: 'flashcards',
  is_public: 'is_public',
  created_at: 'created_at',
  updated_at: 'updated_at',
  is_ai_generated: 'is_ai_generated'
};

exports.Prisma.NoteScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  notes_content: 'notes_content',
  is_public: 'is_public',
  created_at: 'created_at',
  updated_at: 'updated_at',
  is_ai_generated: 'is_ai_generated'
};

exports.Prisma.QuizScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  quiz_content: 'quiz_content',
  title: 'title',
  description: 'description',
  is_public: 'is_public',
  created_at: 'created_at',
  updated_at: 'updated_at',
  is_ai_generated: 'is_ai_generated',
  is_randomized: 'is_randomized',
  timed_quiz: 'timed_quiz'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  tag_name: 'tag_name',
  created_at: 'created_at'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  title: 'title',
  post_body: 'post_body',
  created_at: 'created_at',
  updated_at: 'updated_at',
  is_public: 'is_public'
};

exports.Prisma.PostTagScalarFieldEnum = {
  tag_id: 'tag_id',
  post_id: 'post_id'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  parent_comment_id: 'parent_comment_id',
  post_id: 'post_id',
  user_id: 'user_id',
  comment_body: 'comment_body',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.PostVoteScalarFieldEnum = {
  user_id: 'user_id',
  post_id: 'post_id',
  vote_type: 'vote_type'
};

exports.Prisma.CommentVoteScalarFieldEnum = {
  user_id: 'user_id',
  comment_id: 'comment_id',
  vote_type: 'vote_type'
};

exports.Prisma.PostAttachmentScalarFieldEnum = {
  id: 'id',
  post_id: 'post_id',
  resource_type: 'resource_type',
  note_id: 'note_id',
  flashcard_id: 'flashcard_id',
  quiz_id: 'quiz_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.QuizAttemptScalarFieldEnum = {
  id: 'id',
  quiz_id: 'quiz_id',
  user_id: 'user_id',
  started_at: 'started_at',
  completed_at: 'completed_at',
  answer_data: 'answer_data',
  is_public: 'is_public',
  duration: 'duration',
  score: 'score'
};

exports.Prisma.ReportScalarFieldEnum = {
  id: 'id',
  reported_by_id: 'reported_by_id',
  reported_post_id: 'reported_post_id',
  reported_comment_id: 'reported_comment_id',
  description: 'description',
  reported_target_type: 'reported_target_type',
  reported_at: 'reported_at'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  recipient_id: 'recipient_id',
  actor_id: 'actor_id',
  type: 'type',
  resource_id: 'resource_id',
  resource_type: 'resource_type',
  message: 'message',
  is_read: 'is_read',
  created_at: 'created_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ResourceType = exports.$Enums.ResourceType = {
  NOTE: 'NOTE',
  QUIZ: 'QUIZ',
  FLASHCARD: 'FLASHCARD'
};

exports.ReportTargetType = exports.$Enums.ReportTargetType = {
  POST: 'POST',
  COMMENT: 'COMMENT'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  COMMENTED: 'COMMENTED',
  REPLIED: 'REPLIED',
  OBTAINED_BADGE: 'OBTAINED_BADGE',
  CHANGED_NAME: 'CHANGED_NAME',
  CHANGED_EMAIL: 'CHANGED_EMAIL',
  CHANGED_PASSWORD: 'CHANGED_PASSWORD',
  REPORTED: 'REPORTED',
  DELETED_POST_BY_REPORT: 'DELETED_POST_BY_REPORT',
  DELETED_COMMENT_BY_REPORT: 'DELETED_COMMENT_BY_REPORT'
};

exports.Prisma.ModelName = {
  User: 'User',
  Flashcard: 'Flashcard',
  Note: 'Note',
  Quiz: 'Quiz',
  Tag: 'Tag',
  Post: 'Post',
  PostTag: 'PostTag',
  Comment: 'Comment',
  PostVote: 'PostVote',
  CommentVote: 'CommentVote',
  PostAttachment: 'PostAttachment',
  QuizAttempt: 'QuizAttempt',
  Report: 'Report',
  Notification: 'Notification'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
